version: '3.1'

services:

  jupyter:
    image: jupyter/pyspark-notebook
    restart: always
    command: /bin/bash -c "start.sh jupyter notebook --NotebookApp.token=''"
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./workspace/:/home/jovyan/workspace
